# Generated by Django 5.2.1 on 2025-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
