
FROM python:3.13.3-alpine3.20

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /django

# Install system dependencies
RUN apk update && apk add --no-cache \
    postgresql-dev \
    python3-dev \
    gcc \
    musl-dev \
    build-base \
    linux-headers 


RUN pip install --upgrade pip

# Install watchdog for hot reloading
RUN pip install watchdog

COPY requirements.txt .

RUN  pip install --no-cache-dir -r requirements.txt